services:
  code-server:
    container_name: code-server
    image: lscr.io/linuxserver/code-server:4.96.2-ls248
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Brussels
      #- PASSWORD=password #optional
      #- HASHED_PASSWORD= #optional
      #- SUDO_PASSWORD=password #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - code-server-config:/config
      - code-server-workspace:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
# volumes for mapping data,config and log
volumes:
  code-server-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./config"
  code-server-workspace:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./../"
